export const UNIVERSAL_TEXT = {
  deep_marine_mind: "Deep Marine Mind",
  welcome_to_deep_marine_mind: "Welcome to Deep Mariner Mind",
  login_into_your_account: "Login into your Account",
  welcome_back_access_your_account: "Welcome back Access your account",
  drop_your_email: "Drop your email for lightening quick seafarer recruitment.",
  login: "Login",
  validate_email: "Please provide valid email",
  validate_mobile: "Please provide valid mobile number",

  oceanic_ventures: "Oceanic ventures",
  vessel_with_open_positions: "Vessels with open positions",
  verify_email: "Let's verify your email address",
  create_strong_password: "Let's create a strong password",
  continue: "Continue",
  welcome_onboard: "Welcome onboard! Tell us a bit about yourself!",
  optional: "optional",
  organisation_profile: "Let's set up your organisation profile",
  company_contact_details: "Share your company's contact details",
  preview_company_profile: "Preview Company profile",
  looking_good: "Looking good! Here’s your organisation profile",
  add_fleet: "Add Fleet",
  add_team: "Add Team",
  company_details: "Share your company's contact details",
  address: "Address",
  social_links: "Social links",
  add_fleet_details: "Let’s add your fleet details",
  upload_fleet: "Upload Fleet details",
  add_manually: "Add fleet Manually",
  retry: "Retry upload Again",
  fleet_overview: "Go to Fleet Overview",
  fleet_details: "Looking great! here’s your fleet details.",
  home: "Take me to Home ",
  close: "Close",
  news_tailored_for_you: "News tailored for you",
  create_job: "Create A Job",
  frequent_questions: "Frequently asked questions",
  ship_operate: "In which industry does your ship operate?",
  vessel_type: "What’s the type of vessel for your ship?",
  vessel_details: "Add your vessel details",
  add_ship: "Add Ship",
  view_vessel_details: "Looking good! Here’s your vessel details",
  add_another_ship: "Add Another Ship",
  add_team_member: "Add your team members & Define their rights",
  add_and_continue: "Add & Continue",
  add_another_member: "Add Another Member",
  add_vessel: "Add Vessels",
  select_vessel_name: "Select vessel name",
  notifications: "Notifications",
  daily_view_plan: "Daily views plan",
  perfect_candidate: "Keep the search for the perfect candidate going.",
  buy_now: "Buy Now",
  how_profile_view_credits_works: "How profile view credits works",
  more_view_credit: "If you need more profile view credit?",
  view_balance: "View Balance",
  congratulations: "Congratulations",
  vessel_and_voyage_information: "Tell us about vessel & voyage information",
  hiring_position: "Tell us about the position you are hiring for",
  employment_nature: "What’s the nature of this employment?",
  salary_nature: "What should be the nature of the salary?",
  employee_nature: "Are there any employee amenities?",
  nationality_license:
    "What are the min. experience, nationality, & licenses required?",
  qualification_skills:
    "Please mention any other required qualification or skills ",
  review_job_post: "Review job post",
  review_job_detail: "Review job details",
  post_job: "Post job now",
  save_draft: "Save as a draft",
  edit_job: "Edit job details",
  filter: "Filter",
};
export const INPUT_FIELDS = {
  email: {
    label: "Email ID",
    placeholder: "e.g john.doe@ocenic.com",
    type: "INPUT",
  },
  company_email: {
    label: "Company email ID",
    placeholder: "e.g:careers@oceanic.co",
    type: "INPUT",
  },
  password: {
    label: "Password",
    placeholder: "Render image from figma",
    type: "INPUT",
  },
  name: {
    label: "Full name",
    placeholder: "e.g John Doe",
    type: "INPUT",
  },
  phone: {
    label: "Mobile Number",
    placeholder: "Enter your number",
    type: "INPUT",
  },
  contact: {
    label: "Contact number",
    placeholder: "Enter your number",
    type: "INPUT",
  },
  Organisation_name: {
    label: "Organisation name",
    placeholder: "eg:Oceanic ventures",
    type: "INPUT",
  },
  about: {
    label: "About company",
    placeholder:
      "Provide a brief overview of your company, such as 'With 280 modern ships and 16,600 employees across 400 offices in 140 countries, [Company Name] is a leading global player in [industry].",
    type: "INPUT",
  },
  addressline_1: {
    label: "Address line 1",
    placeholder: "Enter address line 1",
    type: "INPUT",
  },
  addressline_2: {
    label: "Address line 2",
    placeholder: "Enter address line 2",
    type: "INPUT",
  },
  pincode: {
    label: "pincode",
    placeholder: "Enter  pin code",
    type: "INPUT",
  },
  salary: {
    label: "Salary ",
    placeholder: "Add salary",
    type: "INPUT",
  },
  additional_note: {
    label: "Enter additional notes ",
    placeholder:
      "Specify any preferred qualifications or skills for eg: Italian cuisine, etc..",
    type: "INPUT",
  },
};
export const DROPDOWN_FIELD = {
  country: {
    label: "Country",
    type: "DROPDOWN",
    placeholder: "Select your country ",
  },
  state: {
    label: "State",
    type: "DROPDOWN",
    placeholder: "Select your state",
  },
  city: {
    label: "City",
    type: "DROPDOWN",
    placeholder: "Select your city",
  },
  engine_type: {
    label: "Engine type",
    type: "DROPDOWN",
    placeholder: "Select Engine type",
  },
  cargo_type: {
    label: "Cargo type",
    type: "DROPDOWN",
    placeholder: "Select Cargo type",
  },
  ship_built: {
    label: "Ship built",
    type: "DROPDOWN",
    placeholder: "Select Ship built",
  },
  vessel_access: {
    label: "Vessels access",
    type: "DROPDOWN",
    placeholder: "Select vessel",
  },
  trading_country: {
    label: "Trading Country",
    type: "DROPDOWN",
    placeholder: "Select ",
  },
  port: {
    label: "Port",
    type: "DROPDOWN",
    placeholder: "Add port location ",
  },
  voyage_type: {
    label: "Voyage type",
    type: "DROPDOWN",
    placeholder: "Select ",
  },
  flag: {
    label: "Flag",
    type: "DROPDOWN",
    placeholder: "Select ",
  },
  vessel_name: {
    label: "Vessel name",
    type: "DROPDOWN",
    placeholder: "Select ",
  },
  department: {
    label: "Department",
    type: "DROPDOWN",
    placeholder: "Select ",
  },
  rank: {
    label: "Rank",
    type: "DROPDOWN",
    placeholder: "Select ",
  },
  accepted_Cocos: {
    label: "Accepted CoCs",
    type: "DROPDOWN",
    placeholder: "Select accepted CoCs.. ",
  },
};
